export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SWITCH_ENTRIES_VIEW = 'SWITCH_ENTRIES_VIEW';

export const LIST_SCROLL = 'LIST_SCROLL';

export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';

export const TOGGLE_FILTERS_DRAWER = 'TOGGLE_FILTERS_DRAWER';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';