// / FIREBASE AUTH ACTIONS
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_WITH_PROVIDER_FIREBASE = 'LOGIN_WITH_PROVIDER_FIREBASE';

export const RESET_PASSWORD_BY_EMAIL_START = 'RESET_PASSWORD_BY_EMAIL_START';
export const RESET_PASSWORD_BY_EMAIL_SUCCESS = 'RESET_PASSWORD_BY_EMAIL_SUCCESS';
export const RESET_PASSWORD_BY_EMAIL_ERROR = 'RESET_PASSWORD_BY_EMAIL_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FIREBASE_USER = 'REGISTER_FIREBASE_USER';

export const FETCH_FIREBASE_USER = 'FETCH_FIREBASE_USER';
export const UPDATE_FIREBASE_USER = 'UPDATE_FIREBASE_USER';
export const CHANGE_FIREBASE_USER_PASSWORD = 'CHANGE_FIREBASE_USER_PASSWORD';
export const LOGOUT = 'LOGOUT';
export const CHECK_AUTH = 'CHECK_AUTH';
