export const LOAD_LABELS_START = 'LOAD_LABELS_START';
export const LOAD_LABELS_SUCCESS = 'LOAD_LABELS_SUCCESS';
export const LOAD_LABELS_ERROR = 'LOAD_LABELS_ERROR';

export const RECEIVE_LABEL = 'RECEIVE_LABEL';

export const REMOVE_LABEL_SUCCESS = 'REMOVE_LABEL_SUCCESS';
export const REMOVE_LABEL_ERROR = 'REMOVE_LABEL_ERROR';
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';
export const EDIT_LABEL = 'EDIT_LABEL';
