export const LOAD_ENTRIES_START = 'LOAD_ENTRIES_START';
export const LOAD_ENTRIES_SUCCESS = 'LOAD_ENTRIES_SUCCESS';
export const LOAD_ENTRIES_ERROR = 'LOAD_ENTRIES_ERROR';

export const LOAD_ENTRIES_COUNT_START = 'LOAD_ENTRIES_COUNT_START';
export const LOAD_ENTRIES_COUNT_SUCCESS = 'LOAD_ENTRIES_COUNT_SUCCESS';
export const LOAD_ENTRIES_COUNT_ERROR = 'LOAD_ENTRIES_COUNT_ERROR';

export const LOAD_ENTRIES_DATES_START = 'LOAD_ENTRIES_DATES_START';
export const LOAD_ENTRIES_DATES_SUCCESS = 'LOAD_ENTRIES_DATES_SUCCESS';
export const LOAD_ENTRIES_DATES_ERROR = 'LOAD_ENTRIES_DATES_ERROR';

export const RECEIVE_ENTRIES = 'RECEIVE_ENTRIES';
export const RECEIVE_ALL_ENTRIES = 'RECEIVE_ALL_ENTRIES';
export const RECEIVE_ENTRY = 'RECEIVE_ENTRY';
export const SAVE_DUMMY_ENTRY = 'SAVE_DUMMY_ENTRY';
export const REMOVE_ENTRY_SUCCESS = 'REMOVE_ENTRY_SUCCESS';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const CREATE_ENTRY_SUCCESS = 'CREATE_ENTRY_SUCCESS';
export const ENTRY_SAVE_SUCCESS = 'ENTRY_SAVE_SUCCESS';
export const SHOULD_LOAD_ONE_YEAR = 'SHOULD_LOAD_ONE_YEAR';
export const DISABLE_LOAD_ONE_YEAR = 'DISABLE_LOAD_ONE_YEAR';

export const SELECT_ENTRY = 'SELECT_ENTRY';
export const DESELECT_ENTRY = 'DESELECT_ENTRY';
export const FILTER_ENTRIES = 'FILTER_ENTRIES';